In [3]:
import pandas as pd
import pymongo
import json
import os

from dotenv import load_dotenv
load_dotenv()


print(pd.Timestamp.now() )
print("-")

print("initializing variables")
dbuser = "backend"
dbpass = os.environ["backend"]
dbconn = os.environ["connpython"]
origin = os.environ["origin"]
local = os.environ["originlocal"]

print("reading data file")
dbdf = pd.read_pickle("finaldf.data")

print("creating state and year")
dbdf["validade"] = "2022"
dbdf["estado"] = "SP"

# print("exporting df xlsx")
# if os.path.exists("tabela-2022.xlsx"):
#   os.remove("tabela-2022.xlsx")
# dbdf.to_excel("tabela-2022.xlsx")

# print("exporting df csv")
# if os.path.exists("tabela-2022.csv"):
#   os.remove("tabela-2022.csv")
# dbdf.to_csv("tabela-2022.csv")

print("converting df to json")
doc = dbdf.to_json(orient = "records")
doc = json.loads(doc)

# print("creating collection")
# db.createCollection("nomes", { collation: { locale: 'pt_BR', strength: 1 } })
# db.nomes.createIndex( { nome: 1} )

print("saving json to mongo atlas")
conn = dbconn.replace("<username>", dbuser).replace("<password>", dbpass)
rs = pymongo.MongoClient(conn)
db = rs.legalfees
col = db.fees
col.insert_many(doc)

print("-")
print(pd.Timestamp.now() )


display(dbdf)

2023-01-02 14:44:16.949846
-
initializing variables
reading data file
creating state and year
converting df to json
saving json to mongo atlas
-
2023-01-02 14:44:24.048437

,codigo,atividade,valor,porcentagem,sequencial,materia,classe,tipo,validade,estado
0,1,ATIVIDADES AVULSAS OU EXTRAJUDICIAIS,,,0000,ATIVIDADES AVULSAS OU EXTRAJUDICIAIS,,,2022,SP
1,1.1,Consulta,"R$ 448,45",,0001,ATIVIDADES AVULSAS OU EXTRAJUDICIAIS,Consulta,,2022,SP
2,1.1.x,a) Consulta em condições excepcionais (com exa...,"R$ 960,96",,0002,ATIVIDADES AVULSAS OU EXTRAJUDICIAIS,Consulta,,2022,SP
3,1.2,Hora intelectual,"R$ 722,65",,0003,ATIVIDADES AVULSAS OU EXTRAJUDICIAIS,,,2022,SP
4,1.3,Acompanhamento ou exame de documentos em órgão...,"R$ 1.011,70",10%,0004,ATIVIDADES AVULSAS OU EXTRAJUDICIAIS,,,2022,SP
...,...,...,...,...,...,...,...,...,...,...
497,29.3,Elaboração de contrato cível para trabalho inf...,"R$ 4.510,14",,0497,ATIVIDADES EM MATÉRIA TRABALHISTA/CÍVEL,,,2022,SP
498,29.4,Elaboração de contrato cível envolvendo public...,"R$ 4.510,14",,0498,ATIVIDADES EM MATÉRIA TRABALHISTA/CÍVEL,,,2022,SP
499,29.5,Elaboração de contrato cível envolvendo public...,"R$ 4.510,14",,0499,ATIVIDADES EM MATÉRIA TRABALHISTA/CÍVEL,,,2022,SP
500,29.6,Elaboração de parecer sobre cumprimento de cot...,"R$ 3.179,65",,0500,ATIVIDADES EM MATÉRIA TRABALHISTA/CÍVEL,,,2022,SP
501,29.7,Ação envolvendo reintegração diante do não cum...,"R$ 1.589,82",,0501,ATIVIDADES EM MATÉRIA TRABALHISTA/CÍVEL,,,2022,SP