In [1]:
import pandas as pd
import numpy as np
import tabula
import pymongo
import json
import os

from dotenv import load_dotenv
load_dotenv()

dbuser = "backend"
dbpass = os.environ["backend"]
dbconn = os.environ["connpython"]
origin = os.environ["origin"]

tabs = tabula.read_pdf(origin, pages="7", lattice=True, multiple_tables=True, java_options="-Dfile.encoding=UTF8",)
print(f"Found {len(tabs)} tables")

#---

df = tabs[1]
cid = list(df.columns.values)[0]
cname = list(df.columns.values)[1]

df.columns.values[0] = "Codigo"
df.columns.values[1] = "Atividade"
df.columns.values[2] = "Valor"
df.columns.values[3] = "Porc"
df["Classe"] = cname
df["Subclasse"] = ""

df['Codigo'] = df['Codigo'].fillna("")
df['Valor'] = df['Valor'].fillna("")
df['Porc'] = df['Porc'].fillna("")

doc = df.to_json(orient = "records")
doc = json.loads(doc)

conn = dbconn.replace("<username>", dbuser).replace("<password>", dbpass)
rs = pymongo.MongoClient(conn)

db = rs.legalfees
col = db.fees
col.insert_many(doc)

display(df)

Found 3 tables

,Codigo,Atividade,Valor,Porc,Classe,Subclasse
0,4.39,Mandado de injunção,"R$ 3.613,24",,Ação de cancelamento de protesto,
1,4.40,Habeas data,"R$ 3.613,24",,Ação de cancelamento de protesto,
2,4.41,Ação negatória ou de abstenção de uso de matér...,"R$ 15.175,62",-,Ação de cancelamento de protesto,
3,4.42,Ação indenizadora por prejuízos decorrentes de...,"R$ 10.117,08",-,Ação de cancelamento de protesto,
4,4.43,Busca e apreensão em matéria de propriedade in...,"R$ 12.285,03",-,Ação de cancelamento de protesto,
5,4.44,Procedimentos administrativos de propriedade i...,"R$ 4.484,52",-,Ação de cancelamento de protesto,
6,4.45,Análise da documentação e pedido de registro d...,"R$ 3.613,24",10%,Ação de cancelamento de protesto,
7,4.46,Opção de nacionalidade,"R$ 2.890,60",,Ação de cancelamento de protesto,